#!/usr/bin/env python3
"""
Generates an animated terminal-style GitHub profile card (dark.svg + light.svg).

Everything you'd normally want to tweak lives in CONFIG / INFO below.
Long values wrap to a new line by themselves, the label column widens itself
for long labels, and the card's height grows to fit whatever you put in
INFO, so you never have to hand-tune a pixel size again.

Stats (repos, stars, followers) are pulled live from the GitHub API when the
script runs in Actions; if the API is unreachable it silently falls back.
"""

import json
import os
import urllib.request
from datetime import datetime, timezone, timedelta
from html import escape
from pathlib import Path

# ----------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------
USERNAME = "ouhidaayoub"

PORTRAIT_FILE = "portrait.txt"   # generated by photo_to_ascii.py

def load_portrait():
    f = Path(__file__).parent / PORTRAIT_FILE
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip("\n").split("\n")
    return ["[ portrait.txt missing ]"]


# (label, value, colour-key)  |  colour-key: key / val / accent / warn / muted
INFO = [
    ("__header__", "ouhida ayoub", ""),
    ("__rule__", "", ""),
    ("Role",     "Third-Year Computer Science Engineering Student · Specialized in Computer Security", "val"),
    ("Education", "CS Dept, Math & CS Faculty, Univ of M. E. B. E. Ibrahimi · BBA, Algeria", "val"),
    ("Focus",    "OS Internals & Kernel · Reverse Engineering · Malware Development · Embedded Systems", "accent"),
    ("__section__", "~/stack", ""),
    ("Languages", "Assembly x86-64 · C · Java · SQL", "val"),
    ("Tools",    "Git · GitHub · Maven · JavaFX · MySQL · SQLite", "val"),
    ("Documentation", "LaTeX · Notion · Word", "val"),
    ("Security", "TOR", "val"),
    ("__section__", "~/projects", ""),
    ("UDDSS",    "Read-only decision-support system for university departments", "warn"),
    ("__section__", "~/learning", ""),
    ("Now",      "Operating System Kernels · Interrupts · Reverse Engineering", "val"),
    ("Also",     "Mathematics & Physics for Computaria", "val"),
    ("__stats__", "", ""),
    ("__section__", "~/reach", ""),
    ("LinkedIn", "linkedin.com/in/ouhidaayoub", "accent"),
    ("Reddit",   "reddit.com/user/ouhidaayoub", "accent"),
    ("Stack Overflow", "stackoverflow.com/users/28003298/ouhida-ayoub", "accent"),
]

THEMES = {
    "dark": {
        "bg": "#0d1117", "panel": "#161b22", "border": "#30363d",
        "text": "#c9d1d9", "muted": "#8b949e", "key": "#3fb950",
        "accent": "#58a6ff", "warn": "#d29922", "art": "#bc8cff",
        "prompt": "#3fb950", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
    "light": {
        "bg": "#ffffff", "panel": "#f6f8fa", "border": "#d0d7de",
        "text": "#1f2328", "muted": "#59636e", "key": "#1a7f37",
        "accent": "#0969da", "warn": "#9a6700", "art": "#8250df",
        "prompt": "#1a7f37", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
}

W = 980
MIN_H = 150            # low floor, just prevents a degenerate tiny card, real content always wins now
ART_X, ART_Y = 30, 86
ART_CW = 3.9          # forced char width (textLength keeps this exact in any font)
ART_LH = ART_CW * 1.72
INFO_X, INFO_Y, INFO_LH = 448, 60, 17.5
RIGHT_MARGIN = 40
CHAR_W = 7.8            # approx monospace advance width at 13px, used for layout math only


def compute_val_layout(info):
    max_label_len = 0
    for label, _value, _ck in info:
        if label and label not in ("__header__", "__rule__", "__blank__",
                                    "__section__", "__stats__"):
            max_label_len = max(max_label_len, len(label))
    label_col = max(90, int(max_label_len * CHAR_W) + 24)
    val_x = INFO_X + label_col
    val_max_chars = max(20, int((W - RIGHT_MARGIN - val_x) / CHAR_W))
    return val_x, val_max_chars


def wrap_value(value, max_chars):
    if len(value) <= max_chars:
        return [value]
    segments = value.split(" · ")
    tokens = []
    for i, seg in enumerate(segments):
        words = seg.split(" ")
        for j, w in enumerate(words):
            tokens.append(("· " + w) if (i > 0 and j == 0) else w)
    lines, cur = [], ""
    for tok in tokens:
        piece = tok if not cur else " " + tok
        if not cur or len(cur) + len(piece) <= max_chars:
            cur += piece
        else:
            lines.append(cur)
            cur = tok
    if cur:
        lines.append(cur)
    return lines


def info_row_height(label, value, max_chars):
    if label == "__rule__":
        return 8
    if label == "__blank__":
        return 10
    if label in ("__header__", "__section__", "__stats__"):
        return INFO_LH
    return INFO_LH * len(wrap_value(value, max_chars))


FOOTER_GAP = 20     # space between the last content row and the footer prompt line
FOOTER_LINE_H = 20  # space between the footer prompt line and the timestamp line
BOTTOM_MARGIN = 12   # small gap so the timestamp text does not clip against the border


def content_bottom_y(info, art_lines, val_max_chars):
    """Where the real content ends: whichever column, art or info, is taller."""
    y = INFO_Y
    for label, value, _ck in info:
        y += info_row_height(label, value, val_max_chars)
    info_bottom = y
    art_bottom = ART_Y + len(art_lines) * ART_LH
    return max(info_bottom, art_bottom)


def measure_height(info, art_lines, val_max_chars):
    bottom = content_bottom_y(info, art_lines, val_max_chars)
    return max(MIN_H, int(bottom + FOOTER_GAP + FOOTER_LINE_H + BOTTOM_MARGIN))


def fetch_stats():
    stats = {"repos": "-", "stars": "-", "followers": "-"}
    try:
        headers = {"User-Agent": "profile-readme"}
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            headers["Authorization"] = f"Bearer {token}"
        req = urllib.request.Request(
            f"https://api.github.com/users/{USERNAME}", headers=headers)
        user = json.load(urllib.request.urlopen(req, timeout=15))
        stats["repos"] = str(user.get("public_repos", 0))
        stats["followers"] = str(user.get("followers", 0))
        stars, page = 0, 1
        while page <= 5:
            req = urllib.request.Request(
                f"https://api.github.com/users/{USERNAME}/repos"
                f"?per_page=100&page={page}", headers=headers)
            repos = json.load(urllib.request.urlopen(req, timeout=15))
            if not repos:
                break
            stars += sum(r.get("stargazers_count", 0) for r in repos)
            page += 1
        stats["stars"] = str(stars)
    except Exception as e:
        print(f"[warn] stats fetch failed: {e}")
    return stats


def render(theme_name, colors, stats, ist_now, H, art_lines, val_x, val_max_chars):
    parts = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
        f'\'JetBrains Mono\', \'Cascadia Code\', Menlo, Consolas, monospace">'
    )
    parts.append(f"""<style>
    .art  {{ fill:{colors['art']}; font-size:6.2px; white-space:pre; }}
    .key  {{ fill:{colors['key']}; font-size:13px; font-weight:700; }}
    .val  {{ fill:{colors['text']}; font-size:13px; }}
    .acc  {{ fill:{colors['accent']}; font-size:13px; }}
    .wrn  {{ fill:{colors['warn']}; font-size:13px; }}
    .mut  {{ fill:{colors['muted']}; font-size:12px; }}
    .hdr  {{ fill:{colors['accent']}; font-size:15px; font-weight:700; }}
    .sec  {{ fill:{colors['muted']}; font-size:12px; letter-spacing:1px; }}
    .ttl  {{ fill:{colors['muted']}; font-size:12px; }}
    .row  {{ opacity:1; animation: fade .35s ease backwards; }}
    @keyframes fade {{ from {{ opacity:0; transform:translateY(3px); }}
                       to   {{ opacity:1; transform:translateY(0); }} }}
    .cur  {{ fill:{colors['prompt']}; animation: blink 1s steps(1) infinite; }}
    @keyframes blink {{ 50% {{ opacity:0; }} }}
    .artline {{ opacity:1; animation: fade .3s ease backwards; }}
    </style>""")
    parts.append(
        f'<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" '
        f'fill="{colors["bg"]}" stroke="{colors["border"]}" stroke-width="1.5"/>'
    )
    parts.append(
        f'<path d="M1 13 a12 12 0 0 1 12 -12 h{W-26} a12 12 0 0 1 12 12 v25 h{-(W-2)} z" '
        f'fill="{colors["panel"]}"/>'
    )
    parts.append(f'<line x1="1" y1="38" x2="{W-1}" y2="38" stroke="{colors["border"]}"/>')
    for i, c in enumerate(["dot1", "dot2", "dot3"]):
        parts.append(f'<circle cx="{24 + i*20}" cy="20" r="6" fill="{colors[c]}"/>')
    parts.append(
        f'<text x="{W/2}" y="24" class="ttl" text-anchor="middle">'
        f'{escape(USERNAME)} — biography</text>'
    )
    parts.append(
        f'<text x="{ART_X}" y="66" class="row" style="animation-delay:.05s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">I might become the next LINUS Torvalds. No?</tspan></text>'
    )
    for i, line in enumerate(art_lines):
        if not line.strip():
            continue
        y = ART_Y + i * ART_LH
        delay = 0.15 + i * 0.012
        tl = len(line) * ART_CW
        parts.append(
            f'<text x="{ART_X}" y="{y:.1f}" class="art artline" xml:space="preserve" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs" '
            f'style="animation-delay:{delay:.2f}s">{escape(line)}</text>'
        )
    y = INFO_Y
    delay = 0.35
    cls_map = {"val": "val", "accent": "acc", "warn": "wrn", "muted": "mut"}
    for label, value, ckey in INFO:
        d = f'style="animation-delay:{delay:.2f}s"'
        if label == "__header__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="hdr row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__rule__":
            parts.append(
                f'<line x1="{INFO_X}" y1="{y-8:.1f}" x2="{W-40}" y2="{y-8:.1f}" '
                f'stroke="{colors["border"]}" class="row" {d}/>'
            )
            y += 8
        elif label == "__blank__":
            y += 10
        elif label == "__section__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="sec row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__stats__":
            stat_txt = (f'repos {stats["repos"]}   ·   stars {stats["stars"]}'
                        f'   ·   followers {stats["followers"]}')
            parts.append(
                f'<text x="{INFO_X}" y="{y:.1f}" class="row" {d}>'
                f'<tspan class="key">⚡</tspan>'
                f'<tspan class="val" dx="8">{escape(stat_txt)}</tspan></text>'
            )
            y += INFO_LH
        else:
            cls = cls_map.get(ckey, "val")
            if label:
                parts.append(
                    f'<text x="{INFO_X}" y="{y:.1f}" class="key row" {d}>{escape(label)}</text>'
                )
            for vline in wrap_value(value, val_max_chars):
                parts.append(
                    f'<text x="{val_x}" y="{y:.1f}" class="{cls} row" {d}>{escape(vline)}</text>'
                )
                y += INFO_LH
        delay += 0.07
    art_bottom = ART_Y + len(art_lines) * ART_LH
    real_bottom = max(y, art_bottom)   # same "taller column wins" rule measure_height() uses
    fy1 = real_bottom + FOOTER_GAP         # footer prompt (upper row)
    fy2 = fy1 + FOOTER_LINE_H              # timestamp (lower row, own line now)
    parts.append(
        f'<text x="{ART_X}" y="{fy1}" class="row" style="animation-delay:{delay+0.1:.2f}s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">Wanna know something? I dive deep, not wide · More? I read documentation for fun</tspan>'
        f'<tspan class="cur" dx="8">█</tspan></text>'
    )
    parts.append(
        f'<text x="{W-34}" y="{fy2}" class="mut" text-anchor="end">'
        f'last updated {ist_now}</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)


def main():
    stats = fetch_stats()
    ist = datetime.now(timezone.utc) + timedelta(hours=5, minutes=30)
    stamp = ist.strftime("%d %b %Y, %H:%M IST")
    art_lines = load_portrait()
    val_x, val_max_chars = compute_val_layout(INFO)
    H = measure_height(INFO, art_lines, val_max_chars)
    print(f"label column: {val_x - INFO_X}px wide, values wrap past {val_max_chars} chars")
    print(f"card height: {H}px (grew from a base of {MIN_H}px)" if H > MIN_H
          else f"card height: {H}px (fits the base size)")
    out = Path(__file__).parent
    for name, colors in THEMES.items():
        svg = render(name, colors, stats, stamp, H, art_lines, val_x, val_max_chars)
        (out / f"{name}.svg").write_text(svg, encoding="utf-8")
        print(f"wrote {name}.svg")


if __name__ == "__main__":
    main()